# Generated by Django 3.0.5 on 2020-04-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartapp', '0003_auto_20200426_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
